// Background plate for the Stations hero (2026-09-26): an EMPTY chapel wall,
// photographed square-on, generated by Gemini. The 14 real station renders
// are then placed onto it by compose_stations_hero.mjs, so every panel is our
// exact design (two Gemini attempts to draw all fourteen itself repeated
// scenes and dropped stations, which would misrepresent the bundle).
import fs from 'node:fs';
import sharp from 'sharp';
const brs = JSON.parse(fs.readFileSync('D:/000 BUNDLE RELIEF STUDIO/_config/config.json', 'utf8').replace(/^\uFEFF/, ''));
const KEY = brs.gemini_api_key, MODEL = 'gemini-3-pro-image';
const prompt = `A photograph of an EMPTY, plain, pale warm limestone wall inside a quiet chapel, shot perfectly square-on to the wall (camera sensor parallel to the wall, no perspective convergence), full frame 35 mm, f/8, tripod, chest height.
LIGHT: soft warm late-morning sunlight from a tall window just outside the frame at the upper left, falling in gentle diagonal shafts across the wall, plus even bounce so the whole wall is readable. The central area of the wall, where artwork will hang in two long rows, is evenly and softly lit, with the sun shafts mostly across the upper part and the edges.
COMPOSITION: 16:9. The wall fills the frame: fine ashlar limestone blocks with thin mortar lines, a stone floor edge at the very bottom, and the end of a simple oak pew entering from the bottom right corner, slightly out of focus. The middle 80 percent of the wall is clear and uninterrupted.
GRADE: natural, filmic, restrained saturation, true warm stone. A real photograph.
ABSOLUTELY NOT: no artwork, no panels, no frames, no crosses, no candles, no text, no numbers, no people, no windows inside the central wall area, no doors, no CGI look.`;
for (let attempt = 1; attempt <= 3; attempt++) {
  const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${KEY}`, { method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }], generationConfig: { imageConfig: { imageSize: '2K', aspectRatio: '16:9' } } }) });
  const j = await r.json();
  const img = (j?.candidates?.[0]?.content?.parts || []).find((p) => p.inlineData?.data || p.inline_data?.data);
  if (!img) { console.log(`attempt ${attempt}: ${(j?.error?.message || 'no image').slice(0, 160)}`); continue; }
  await sharp(Buffer.from(img.inlineData?.data || img.inline_data.data, 'base64')).jpeg({ quality: 94 }).toFile('.mockups/stations/wall.jpg');
  console.log('wrote .mockups/stations/wall.jpg'); process.exit(0);
}
process.exit(1);
