-- Owner review queue for generated marketing images (2026-09-03).
--
-- Nothing generated by AI reaches Pinterest until the owner has looked at it.
-- Every image lands as 'pending'; the admin Marketing Images card shows it with
-- the scene text that produced it, and the owner approves, edits and
-- regenerates, or rejects. Only 'approved' images are used by the Pin art and
-- the feeds.
alter table public.products
  add column if not exists mockup_status text not null default 'pending',
  add column if not exists macro_status text not null default 'pending',
  add column if not exists mockup_scene text;

alter table public.categories
  add column if not exists mockup_status text not null default 'pending',
  add column if not exists mockup_scene text;

create index if not exists products_mockup_review_idx
  on public.products (mockup_status) where mockup_url is not null;

-- Existing rows were generated before review existed: treat them as pending so
-- the owner sees them in the queue rather than silently going live.
update public.products set mockup_status = 'pending' where mockup_url is not null and mockup_status is null;
