-- The CNC Setup Card: what a maker needs before cutting, per design.
--
-- BRS already builds this card (product picture, clamp and zero map, setup
-- dimensions at every panel size, feeds and speeds, carve journey, and how much
-- fine detail survives at each size). It renders from the STL alone. Until now
-- it lived only in the delivery folder on the machine that made it, so a buyer
-- who asked "is there information about this design?" could not be answered.
--
-- This holds the published card so the product page can show it and the
-- delivery can carry it.
alter table public.products add column if not exists setup_card_url text;
comment on column public.products.setup_card_url is
  'Published CNC Setup Card image for this design, generated by BRS from the STL.';
create index if not exists products_setup_card_idx on public.products (id) where setup_card_url is not null;
